// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0EScLOsvLigi5IG5zsIDBmxdiUuSm3c',
    appId: '1:429068991581:web:d7fe447cce2e3e0d9161b4',
    messagingSenderId: '429068991581',
    projectId: 'garbage-classification-ai',
    authDomain: 'garbage-classification-ai.firebaseapp.com',
    storageBucket: 'garbage-classification-ai.firebasestorage.app',
    measurementId: 'G-D9NYNZKH57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKoIJIzieWPN4FpQeEb0JkRIUdTBHw5lU',
    appId: '1:429068991581:android:ddf1e0ad81da16859161b4',
    messagingSenderId: '429068991581',
    projectId: 'garbage-classification-ai',
    storageBucket: 'garbage-classification-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhJ9Lf7P53Y894Esd7Ep5J8-g2hOXwJlY',
    appId: '1:429068991581:ios:0a4dc90cc0cb156e9161b4',
    messagingSenderId: '429068991581',
    projectId: 'garbage-classification-ai',
    storageBucket: 'garbage-classification-ai.firebasestorage.app',
    iosBundleId: 'com.example.garbageClassification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhJ9Lf7P53Y894Esd7Ep5J8-g2hOXwJlY',
    appId: '1:429068991581:ios:0a4dc90cc0cb156e9161b4',
    messagingSenderId: '429068991581',
    projectId: 'garbage-classification-ai',
    storageBucket: 'garbage-classification-ai.firebasestorage.app',
    iosBundleId: 'com.example.garbageClassification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm0EScLOsvLigi5IG5zsIDBmxdiUuSm3c',
    appId: '1:429068991581:web:3fcac10f56266ec79161b4',
    messagingSenderId: '429068991581',
    projectId: 'garbage-classification-ai',
    authDomain: 'garbage-classification-ai.firebaseapp.com',
    storageBucket: 'garbage-classification-ai.firebasestorage.app',
    measurementId: 'G-3BKWKZ8GYB',
  );
}
