name: garbageClassification
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.7
  http: ^1.3.0
  get: ^4.6.6
  theme_provider: ^0.6.0

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.0.0
  # flutter_web_auth: ^0.6.0
  provider: ^6.1.2
  pay: ^3.2.1

  cloud_firestore: ^5.6.7
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.14

flutter:

  uses-material-design: true

  assets:
    - assets/
  